<?php $counterAgentRow = $this->view->getVar('counterAgentRow')?>
<div class="elz d-flex hmn100p dir-y gapVar pVar">
    <div class="elz d-block pVar r3 bg bg-primary bgL5 bsh-default1 p-rel">
        <div class="elz d-flex a-H f-wrap gapH16 gapV8 hmn36">
            <div class="elz d-flex a-H growMax fn20 lh12">
                <a href="/counteragents" class="elz p-rel d-flex a-X w40 mL-Var">
                    <div class="elz p-rel p8 m-8 rCircle cur-pointer opAct07 bgHov bgHov-primary bgHovL-5 bgHovLF5 bgHovFD bgLInvD" title="К поиску контрагентов">
                        <div class="elz p-rel d-flex a-X s16">
                            <div class="elz p-abs d-block mskBef s16 cFillBef bgBef-CC deg270" style="--elzMsk: url('/design/icons/arrow4.svg');"></div>
                        </div>
                    </div>
                </a>
                <div id="counterAgentHeaderTitle" class="elz d-flex grow"><?=$counterAgentRow['counteragent_title']?></div>
            </div>
<?php $rightPanel = $this->view->getVar('mainSectionHeaderRightTemplate')?>
<?if($rightPanel):?>
            <?$this->view->partial($rightPanel)?>
<?endif;?>
        </div>
    </div>

    <?=$this->getContent()?>
</div>