<div class="elz admOGTCdemo <?=$classes?>">

    <div class="elz ogtcIconWrap">
        <div class="elz admManiIcons">
            <div class="elz iconsOuter">
                <?$this->view->partial('partials/widget_uploader_image', $icon)?>
            </div>
        </div>
    </div>

    <div class="elz ogtcContent">
        <div class="elz ogtcTitle rcpOGTCTitle"><?=$title?></div>
        <div class="elz ogtcDescription rcpOGTCDescription"><?=$description?></div>
        <div class="elz ogtcUrl"><?=$site?></div>
    </div>

</div>