<div class="elz d-flex gap8">
    <div class="elizaRightPanelTrigger elz elzButton grow fb150 d-flex a-X al-center r3 bor1 h36 pH12 wmx100p fn12 lh12 cur-pointer trnsStyle trns
                    bg bg-ok bgHovL3 bgActL-10 bgSelL-10
                    br br-ok brFD brLF-10 brL-10 brHovL-15 brSelL-15
                    fn fn-ok-t fnHovL10 fnSelL10
                    bsh bsh-btn bshHov-btnhov bshAct-inset bshSel-inset" data-engine="vue" data-panel="orders" data-widget="add" data-node="1">Добавить заказ</div>

</div>