<?php
namespace Site\Rcp\Controllers;


use Core\Extender\ControllerApp;
use Core\Lib\AjaxFormResponse;


class IndexController extends ControllerApp
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if ($this->user->rcpLogged()) {
            $this->view->setTemplateAfter('rcp_wrap');
        }
    }

    public function indexAction()
    {
        if ($this->user->rcpLogged()) {
            $this->view->pick('index/index_logged');
        }
    }

    public function apiRcp_login()
    {
        $mail = trim($this->request->getPost('mail'));
        $pass = ($this->request->getPost('pass'));
        $status = 'no';
        $formStatus = AjaxFormResponse::ERROR;
        $formText   = $this->t->_('idx_login_error');

        $statusManager = new AjaxFormResponse();


        if ($this->user->loginAsRCP($pass, $mail)) {
            $status = 'yes';
            $formStatus = AjaxFormResponse::SUCCESS;
            $formText   = '';
        }

        $statusManager->setStatus('mail', $formStatus, $formText);
        $statusManager->setStatus('pass', $formStatus, $formText);

        $this->sendResponseAjax([
            'auth'   => $status,
            'fields' => $statusManager->getStatuses()
        ]);
    }
}