<?php $contactNodeId = $this->view->getVar('counterAgentRow')['contact_node_id']?>
<?php $viewModeCards = (int)$this->user->getSetting('counteragent_contacts_view_mode')?>
<div class="elz d-flex grow f-wrap gap8 fb560">

    <div class="pmContactsListMode elz d-flex">
        <input id="counterAgentContactsModeLines" class="counterAgentContactsModeRadio elz hide cLblSib" type="radio"<?if(!$viewModeCards):?> checked="checked"<?endif;?> name="pmContactsMode" value="lines">
        <label for="counterAgentContactsModeLines" class="elz elzButton d-flex a-X rL3 bor1 s36 wmx100p fn12 cur-pointer trnsStyle trns
                                            bg bg-primary bgL0 bgHovL3 bgActL-10 bgLblLingL-10
                                            br br-primary brL-10 brHovL-15 brLblLingL-15
                                            fn fn-primary-t fnLInvD fnHovL-10 fnLblLingL-10
                                            bsh bsh-btn bshHov-btnhov bshAct-inset bshLblLing-inset">
            <span class="elz p-abs d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/list.svg');"></span>
        </label>
        <input id="counterAgentContactsModeCards" class="counterAgentContactsModeRadio elz hide cLblSib" type="radio"<?if($viewModeCards):?> checked="checked"<?endif;?> name="pmContactsMode" value="cards">
        <label for="counterAgentContactsModeCards" class="elz elzButton d-flex a-X rR3 bor1 s36 wmx100p fn12 cur-pointer trnsStyle trns mL-1
                                            bg bg-primary bgL0 bgHovL3 bgActL-10 bgLblLingL-10
                                            br br-primary brL-10 brHovL-15 brLblLingL-15
                                            fn fn-primary-t fnLInvD fnHovL-10 fnLblLingL-10
                                            bsh bsh-btn bshHov-btnhov bshAct-inset bshLblLing-inset">
            <span class="elz p-abs d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/grid.svg');"></span>
        </label>
    </div>

    <?$this->view->partial('forms/select_base', [
        'id' => 'pmContactActiveFilter',
        'name' => 'contact_active',
        'options' => [
            [1, 'Активные'],
            [0, 'Неактивные'],
        ],
        'value' => 1,
        'inputClass' => 'r3 h36'
    ])?>
    <div class="elz d-flex gap8 fb280 grow">
        <div class="elizaRightPanelTrigger elz elzButton grow fb150 d-flex a-X al-center r3 bor1 h36 pH12 wmx100p fn12 lh12 cur-pointer trnsStyle trns
                    bg bg-ok bgHovL3 bgActL-10 bgSelL-10
                    br br-ok brFD brLF-10 brL-10 brHovL-15 brSelL-15
                    fn fn-ok-t fnHovL10 fnSelL10
                    bsh bsh-btn bshHov-btnhov bshAct-inset bshSel-inset" data-panel="contact" data-widget="add" data-node="<?=$contactNodeId?>" data-type="employee">Добавить контакт</div>
        <div class="elizaRightPanelTrigger elz elzButton grow fb150 d-flex a-X al-center r3 bor1 h36 pH12 wmx100p fn12 lh12 cur-pointer trnsStyle trns
                    bg bg-success bgHovL3 bgActL-10 bgSelL-10
                    br br-success brFD brLF-10 brL-10 brHovL-15 brSelL-15
                    fn fn-success-t fnHovL10 fnSelL10
                    bsh bsh-btn bshHov-btnhov bshAct-inset bshSel-inset" data-panel="contact" data-widget="add" data-node="<?=$contactNodeId?>" data-type="service">Добавить службу</div>
    </div>
</div>