<div class="elz d-block grow fb320 pVVar r3 bg bg-primary bgL5 bsh-default1">
    <form id="pmCounteragentsAddForm" method="post" action="" class="elz d-block pH8">
        <label class="elz d-grid grPos fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0 evNone hide">
            <input id="pmCounteragentsAddName" type="text" name="title" value="" placeholder="Заполняется автоматически" class="elz elzInput d-block grPin grY2 w100p bor1 rT3 h40 pL96 pR16 fn12 ellipsis trns2 invPssSib
                                                                                        bg bg-primary bgL10 bgLInvD
                                                                                        br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                                                                        fn fn-primary-t uDisabled">
            <span class="elz d-flex grPin grY2 a-H pH16 z6 evNone">
                <span class="elz p-rel a-H d-flex trns2">Название:</span>
            </span>
        </label>
        <label class="elz d-grid grPos mT-1 fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0">
            <input id="pmCounteragentsAddINN" type="text" name="inn" value="" placeholder="Название или ИНН" class="elz elzInput d-block grPin grY2 w100p bor1 r3 h40 pL64 pR16 fn12 ellipsis trns2 invPssSib
                                                                                bg bg-primary bgL10 bgLInvD
                                                                                br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                                                                fn fn-primary-t">
            <span class="elz d-flex grPin grY2 a-H pH16 z6 evNone">
                <span class="elz p-rel a-H d-flex trns2">Поиск:</span>
            </span>
        </label>

        <input id="pmCounteragentsAddDaData" type="hidden" name="dadata" value="">
    </form>
</div>