<div class="extendTile elz d-flex a-X gap8 hmn40 cur-pointer pL12 pR12 bgHov bgHov-primary bgHovL-5 bgHovLF5 bgHovFD bgLInvD bgSel bgSel-secondary fnSel fnSel-secondary-t opHovOut cSelOut<?if($selected ?? 0):?> sel<?endif;?>" title="<?=$descr?>" data-value="<?=$value?>" data-category="<?=($category ?? 0)?>">
    <div class="elz d-block growX bold"><?=$title?></div>
<?$counts = $counts ?? []?>
<?for($a = 0, $len = sizeof($counts); $a < $len; $a++):?>
    <?$count = $counts[$a]?>
    <div class="elz p-rel d-flex a-X  h20 wmn20 fn10 r2 al-center bold bg bg-primary bgSelIn-secondary bgL-15 bgLInvD fnSelIn-secondary-t" title="<?=$count['title'].$count['count']?>"><?=$count['count']?></div>
<?endfor;?>
    <div class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC op01 opHovIn10" style="--elzMsk: url('/design/icons/cross1.svg');"></div>
</div>