version: "3"

networks:
  lan:
    driver: bridge

services:

  php-fpm:
    build:
      dockerfile: php-fpm/Dockerfile
      args:
        - PHP_FPM_PORT=${PHP_FPM_PORT}
        - PHP_VER=${PHP_VER}
    volumes:
      - ${PROJECT_HOME_DIR}:/var/www:cached
    ports:
      - 9000:${PHP_FPM_PORT}
      - 9003:9003
      - 22:22
    networks:
      - lan

  nginx:
    build:
      dockerfile: nginx/Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=${PHP_FPM_PORT}
    volumes:
      - ${PROJECT_HOME_DIR}:/var/www
    ports:
      - ${WWW_PORT}:80
      - ${HTTPS_WWW_PORT}:443
    depends_on:
      - php-fpm
    networks:
      - lan

  postgres:
    build: 
      dockerfile: postgres/Dockerfile
      args:
        - PSQL_DB=${PSQL_DB}
        - PSQL_USER=${PSQL_USER}
        - PSQL_PASSWORD=${PSQL_PASSWORD}
    environment:
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    volumes:
        - ${PSQL_DATA}:/var/lib/postgresql/data
    ports:
      - "${PSQL_PORT}:5432"
    networks:
      - lan  

# run:
# docker-compose build
# docker-compose up
