<?php $name = $name ?? '';?>
<?php $layout = $layout ?? 'columns_1';?>
<?php $width = $width ?? 'w960';?>
<?php $height = $height ?? 'h640';?>
<?php $search = $search ?? 'defaultSearchName';?>
<?php $icon = $icon ?? 'search';?>
<?php $title = $title ?? 'set: title'; ?>

<?$iconExpl = explode(' ', $icon)?>
<?$iconSvg = $iconExpl[0]?>
<?$iconSize = $iconExpl[1] ?? 's16'?>
<div class="elizaSearchPanelExtend elz pmAdvSec           p-fixed d-flex dir-y r3 <?=$width?> <?=$height?> fn12 z5 bsh-default3 fn fn-primary-t bg bg-primary bgL5 hide" data-engine="<?=$search?>" data-name="<?=$name?>" data-type="title">
    <div class="elz d-flex a-R hEP pL8 borB1 br br-primary brLF10 brFD brLInvD">
        <div class="elz d-flex growX fn16 a-H">
            <div class="elz d-flex a-X s40">
                <div class="elz d-block p-rel mskBef <?=$iconSize?> cFillBef bgBef-CC mskBef-contain" style="--elzMsk: url('/design/icons/<?=$iconSvg?>.svg');"></div>
            </div>
            <div class="elz d-block growX"><?=$title?></div>
        </div>
        <div class="elz d-flex gap8 pH8 or3 noShrink">
            <div class="elz p-rel d-flex">
                <div class="elizaSearchPanelClose elz p-rel d-flex a-X gap8 cur-pointer opAct07">
                    <div class="elz p-rel d-flex a-X s40 rCircle bgSelIn bgSelIn-ok fnHov fnHovL-10 fnHovLInvD">
                        <div class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/cross1.svg');"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="elz d-flex growY">
        <?$this->view->partial('partials/eliza_search/panels/layouts/'.$layout)?>
    </div>
</div>
