<?php
$type = $type ?? 'text';
$value = $value ?? '';
$title = $title ?? '';
$placeholder = $placeholder ?? '';
$icon = $icon ?? '';
$name = $name ?? '';

?>
<label class="elizaIForm2 elz d-grid grPos fn fnLInvD fn-primary-t fnL20 fnHovL10 fnFow-focus fnFowL0">
    <input name="<?=$name?>" type="<?=$type?>" value="<?=$value?>" placeholder="<?=$placeholder?>" class="elizaIFormInput elz d-block grPin grY2 w100p borB2 h48 pL32 ellipsis trns2 invPssSib br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0 fn fn-primary-t" />

    <span class="elz d-flex grPin grY2 a-X borB2 evNone">
        <span class="elz p-rel d-flex a-X s24 trns2">
            <span class="elizaIFormIconL elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/<?=$icon?>.svg');"></span>
        </span>

        <span class="elizaIFormIconRWrap elz p-rel growZ d-flex a-PR invisible">
            <span class="elizaIFormIconRStatus elz p-rel d-flex a-X r2 trns2 cur-help opHovOut bgHov bgHov-error fn fn-error fnHov-error-t">
                <span class="elizaIFormIconRText elz fn-8 bold al-right pH8 op0 opHovIn10 trns2 trnsVis oH ellipsis"></span>
                <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                    <span class="elizaIFormIconR elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style=""></span>
                </span>
            </span>
        </span>
    </span>

    <span class="elizaIFormLabel elz d-block fn-8 trns2 invPssLing"><?=$title?></span>
</label>