<div class="elz d-flex hmn100p dir-y gapVar pVar">





        <div class="elz d-block pVar r3 bg bg-primary bgL5 bsh-default1">
            <div class="elz d-flex a-H f-wrap gapH16 gapV8 hmn36">
                <div class="elz d-flex a-H growMax fn20 lh12">

                    <div class="elz d-flex a-H growMax fn20 lh12">

                        <div class="elz p-rel d-flex a-X w40 mL-Var">
                            <div class="elz p-rel p8 m-8 rCircle cur-pointer opAct07 bgHov bgHov-primary bgHovL-5 bgHovLF5 bgHovFD bgLInvD">
                                <div class="elz p-rel d-flex a-X s16">
                                    <div class="elz p-abs d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/address.svg');"></div>
                                </div>
                            </div>
                        </div>

                        <div class="elz d-flex grow">Юридическая информация контрагента</div>
                    </div>
                </div>
            </div>
        </div>







    <div class="elz d-flex grow">
        <div id="pmCounteragentsAddDataInfoPlaceHolder" class="elz d-flex growX r3 bg bg-primary bgL5 bsh-default1">
            <div class="elz d-flex grow dir-y a-X p16 gap16">
                <div class="elz p-rel d-block mskBef s120 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/info24-outline.svg');"></div>
                <div class="elz d-block al-center fn16">Введите имя контрагента или ИНН</div>
            </div>
        </div>
        <?$this->view->partial('counteragents/partials/legal_requisites')?>
    </div>

</div>
