
<div id="pmCounteragentsAddINNList" class="elz d-flex grow fb320 dir-y gap8 lh15 s-stretch">
</div>

<div class="elz p-sticky grow fb320 p-B pVar m-Var bg bg-primary">
    <div class="elz p-sticky d-block pVVar grow r3 bg bg-primary bgL5 bsh-default1">
        <div class="elz d-flex a-X gap8 pH8">
            <button form="pmCounteragentsAddForm" id="pmCounteragentsAddSend" class="elz elzButton d-flex a-X r3 bor1 h36 pH24 fn12 lh12 al-center cur-pointer trnsStyle trns
                        bg bg-ok bgHovL3 bgActL-10 bgSelL-10
                        br br-ok brFD brLF-10 brL-10 brHovL-15 brSelL-15
                        fn fn-ok-t fnHovL10 fnSelL10
                        bsh bsh-btn bshHov-btnhov bshAct-inset bshSel-inset uDisabled" disabled="disabled">Добавить</button>
        </div>
    </div>
</div>