<?$sitesList = $this->view->getVar('sitesList')?>
<?$groupsList = $this->view->getVar('groupsList')?>
<?$membersList = $this->view->getVar('membersList')?>
<?$rightsList = $this->view->getVar('rightsList')?>

<?$appRow = $this->view->getVar('appRow')?>
<?$langList = [[1, 'RU'], [2, 'EN']]?>
<?$t = $this->view->t?>

<div id="ipRcpEditAppId" data-id="<?=$appRow['app_id']?>" class="elz strCLSitem wrap flexible padBMedium padRMedium">
    <?$this->view->partial('partials/forms/forms_section', [
        'title'  => $t->_('app_edit_caption1'),
        'formId' => 'ipRcpEditAppEdit',
        'formAction' => '/apps/api/app_edit?app_id='.$appRow['app_id'],
        'formData'   => 'data-app="'.$appRow['app_id'].'"',
        'submitTitle' => $t->_('app_edit_save'),
        'langed' => ['list' => [[1, 'RU'], [2, 'EN']], 'id' => 'ipRcpEditAppEditLang', 'name' => 'lang', 'class' => ''],
        'fieldList' => [
            [
                'field'  => 'checkbox',
                'ftitle' => $t->_('app_edit_guest'),
                'fdescr' => $t->_('app_edit_guest_d'),
                'wtitle' => 'wmn240',
                'id' => '',
                'text' => $t->_('app_edit_guest_a'),
                'classes' => 'rcpAppEditAccessMask maskPos1',
                'name' => '',
                'checked' => (int)($appRow['app_access'] & '100')

            ],
            [
                'field'  => 'input',
                'ftitle' => $t->_('app_edit_name'),
                'fdescr' => $t->_('app_edit_name_d'),
                'wtitle' => 'wmn240',

                'type'   => 'text',
                'placeholder' => $t->_('app_edit_name_p'),
                'value' => $appRow['app_name'],
                'name'  => 'name'
            ],
            [
                'field'  => 'input',
                'ftitle' => $t->_('app_edit_title'),
                'fdescr' => $t->_('app_edit_title_d'),
                'wtitle' => 'wmn240',
                'type'   => 'text',
                'placeholder' => $t->_('app_edit_title_p'),
                'value' => $appRow['app_title'],
                'name'  => 'title'
            ],
            [
                'field'  => 'input',
                'ftitle' => $t->_('app_edit_slogan'),
                'fdescr' => $t->_('app_edit_slogan_d'),
                'wtitle' => 'wmn240',
                'type'   => 'text',
                'placeholder' => $t->_('app_edit_slogan_p'),
                'value' => $appRow['app_slogan'],
                'name'  => 'slogan'
            ],
            [
                'field'  => 'textarea',
                'ftitle' => $t->_('app_edit_description'),
                'fdescr' => $t->_('app_edit_description_d'),
                'wtitle' => 'wmn240',
                'placeholder' => $t->_('app_edit_description_p'),
                'value' => $appRow['app_description'],
                'name'  => 'description'
            ]
        ]
    ])?>

</div>


<div id="ipRcpEditAppPermissionLists" class="elz strCLSitem wrap flexible padBMedium padRMedium">
    <div class="elz strCLSitem marLMedium marTMedium wmn320 grow flexible">
        <div class="elz admCLSwrap flexible shadowed">

            <div class="elz admHeader admWBordered">
                <div class="elz admCaption">
                    <h2 class="elz admTitle">Список сайтов</h2>
                </div>
                <div class="elz strCLSitem marLMedium marRMedium">
                    <?=\Core\Builder\MustacheForms::checkbox('', 'Доступ с указанных сайтов', 'rcpAppEditAccessAllSites', '', (int)$appRow['app_all_sites'] ? 0 : 1, '', 'left')?>
                </div>
            </div>

            <div class="elz admBody">

                <div class="elz strCLSitem">
                    <div class="elz elzCLStableWrap padTSmaller">
                        <table class="elz elzCLStable striped">
                            <tbody class="elz tbody" id="rcpAppEditSitesList">
                            <?for($a = 0, $len = sizeof($sitesList); $a < $len; $a++):?>
                                <?$site = $sitesList[$a]?>
                                <tr class="rcpAppEditSiteContainer" data-site="<?=$site['site_id']?>">
                                    <td class="pad padVSmaller padHMedium elzCbox h36 wmn200">
                                        <div class="elz elzText nowrap">Сайт: <b class="bb strong"><?=$site['site_name']?></b></div>
                                    </td>
                                    <td class="pad padVSmaller padHMedium elzCbox h36 compressed">
                                        <?=\Core\Builder\MustacheForms::checkbox('', 'Включить', 'rcpAppEditSiteToggle', '', (int)$site['app_linked'], '', 'left')?>
                                    </td>
                                </tr>
                            <?endfor;?>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="elz strCLSitem marLMedium marTMedium wmn320 grow flexible">
        <div class="elz admCLSwrap flexible shadowed">

            <div class="elz admHeader admWBordered">
                <div class="elz admCaption">
                    <h2 class="elz admTitle">Список групп</h2>
                </div>
                <div class="elz strCLSitem marLMedium marRMedium">
                    <?=\Core\Builder\MustacheForms::checkbox('', 'Доступ для указанных групп', 'rcpAppEditAccessMask maskPos2', '', (int)($appRow['app_access'] & '010'), '', 'left')?>
                </div>
            </div>

            <div class="elz admBody">

                <div class="elz strCLSitem">
                    <div class="elz elzCLStableWrap padTSmaller">
                        <table class="elz elzCLStable striped">
                            <tbody class="elz tbody" id="rcpAppEditGroupsList">

<?for($a = 0, $len = sizeof($groupsList); $a < $len; $a++):?>
    <?$group = $groupsList[$a]?>

    <tr class="rcpAppEditGroupContainer" data-group="<?=$group['group_id']?>">
        <td class="pad padVSmaller padHMedium elzCbox h36 wmn200">
            <div class="elz elzText nowrap"><b class="bb strong"><?=$group['group_title']?></b> [<?=$group['group_name']?>]</div>
        </td>
        <td class="pad padVSmaller padHMedium elzCbox h36 compressed">
            <?=\Core\Builder\MustacheForms::checkbox('', 'Включить', 'rcpAppEditGroupToggle', '', (int)$group['app_linked'], '', 'left')?>
        </td>
    </tr>
<?endfor;?>
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
    <div class="elz strCLSitem marLMedium marTMedium wmn320 grow flexible">
        <div class="elz admCLSwrap flexible shadowed">

            <div class="elz admHeader admWBordered">
                <div class="elz admCaption">
                    <h2 class="elz admTitle">Список пользователей</h2>
                </div>
                <div class="elz strCLSitem marLMedium marRMedium">
                    <?=\Core\Builder\MustacheForms::checkbox('', 'Доступ для указанных пользователей', 'rcpAppEditAccessMask maskPos3', '', (int)($appRow['app_access'] & '001'), '', 'left')?>
                </div>
            </div>

            <div class="elz admBody">
                <div class="elz strCLSitem padVSmaller padHSmall borB1">
                    <?=\Core\Builder\MustacheForms::input('text', 'Введите псевдоним пользователя', '', 'ic-user', 'rcpAppEditMemberSearch')?>
                </div>
                <div class="elz strCLSitem">
                    <div class="elz elzCLStableWrap padTSmaller">
                        <table class="elz elzCLStable striped">
                            <tbody class="elz tbody" id="rcpAppEditMembersList">
                            <?for($a = 0, $len = sizeof($membersList); $a < $len; $a++):?>
                                <?=$this->view->partial('apps/member_tr', $membersList[$a])?>
                            <?endfor;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<?$this->view->partial('rights/rights_widget', [
    'rightsList' => $rightsList,
    'rightsWidgetGetParam' => 'app_id='.$appRow['app_id'],
    'rightsWidgetId' => 'ipRcpEditAppRights'
])?>