<tr class="rcpAppEditMemberContainer">
    <td class="pad padVSmaller padHMedium elzCbox h24 wmn200">
        <div class="elz strCLSitem flexible middle elzCLSuName <?=$member_gender?>">
            <div class="elz strCLSitem">
                <div class="elz elzIcon smallest rad">
                    <i class="elz main smallest elzIc ic-user"></i>
                </div>
            </div>
            <div class="elz strCLSitem marLSmaller grow w0"><?=$member_nick?></div>
        </div>
    </td>
    <td class="pad padVSmaller padHMedium elzCbox h24 compressed memberUnlink" data-id="<?=$member_id?>">
        <div class="elz strCLSitem elzLink hovering elzPLT" data-fn="red" data-bg="transparent">
            <div class="elz elzIcon medium rad">
                <i class="elz main smallest elzIc ic-cross"></i>
            </div>
        </div>
    </td>
</tr>