<div class="extendItem elz d-flex a-H gap8 p16 r3 bor1 br br-primary brL-10 brHovL-15 brSelL-20 brLInvD bg bg-primary bgSelL-15 bgSelLInvL cur-pointer opAct07<?if($selected):?> sel<?endif;?>" title="<?=htmlspecialchars($counteragent_title)?>" data-value="<?=$counteragent_id?>">
    <div class="extendTitle elz d-block  grow lh15"><?=$counteragent_title?></div>
    <div class="elz d-flex noShrink a-H gap4 p4 r3 fn11 bold bg bg-primary bgL-10">
        <div class="mskIcon elz d-block p-rel noShrink mskBef s12 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/rules.svg');"></div>
        <div class="elz d-block"><?=$contract_count?></div>
    </div>
</div>
