<?php $title = $title ?? 'УКАЖИ НАЗВАНИЕ'?>
<?php $tag = $tag ?? 'button'?>
<?php $type = isset($type) ? 'type="'.$type.'"' : ''?>

<<?=$tag?> <?=$type?> class="elz elzButton d-flex a-X r3 bor1 h36 pH16 wmx100p fn12 cur-pointer trnsStyle trns
bg bg-error bgHovL3 bgActL-10 bgSelL-10
br br-error brFD brLF-10 brL-10 brHovL-15 brSelL-15
fn fn-error-t fnHovL10 fnSelL10
bsh bsh-btn bshHov-btnhov bshAct-inset bshSel-inset"><?=$title?></<?=$tag?>>