<?php $empty = $empty ?? ''?>
<?php $expandContClass = $expandContClass ?? ''?>
<div class="pmContentExpandContainer<?=$expandContClass?> formWrap elz d-flex a-H f-wrap gapH16 gapV8 pV16 borT1 br br-primary brL-10 brLInvD showSelOut hideSelOut invSelOut showHovOut" data-name="<?=$name?>">
    <div class="elz d-block fb120 bold"><?=$title?>:</div>
    <div class="elz p-rel d-flex dir-y a-V fb320 grow hmn18">
        <div title="Редактировать" class="formToggle elz p-abs p-R d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5 hideSelIn showHovIn">
            <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/pencil.svg');"></div>
        </div>

        <div class="elz p-abs p-F d-flex dir-y a-V mV-10 showSelIn z1">
            <form method="post" action="<?=$action?>" class="elz d-grid grTV010 grPos fn fn-primary-t fnL20 s100p fnLInvD fnHovL10 fnFow-focus fnFowL0">
                <input type="hidden" name="<?=$name?>_id" value="<?=$content['id']?>">
                <input type="text"
                       name="<?=$name?>"
                       value="<?=htmlspecialchars($content['title'])?>"
                       class="elz elzInput d-block grPin grY2 s100p bor1 pL16 pR40 r3 fn12 ellipsis trns2 invPssSib
                              bg bg-primary bgL10 bgLInvD
                              br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                              fn fn-primary-t">
                <span class="elz d-flex grPin grY2 a-H bor1 pH7 z6 evNone">
                    <span class="elz p-rel growX d-flex a-PR">
                        <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                            <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                            </span>
                        </button>
                    </span>
                </span>
            </form>
            <div class="formAutocomplete elz p-abs d-block p-H pi-T mH4 mT16 z10 r2 oAuto hmx320 bsh-default7 bg bg-primary bgL5 fn fn-primary-t hide">

            </div>
        </div>
        <div class="elz d-block invSelIn pR40">
            <div class="elz d-flex a-H grow gap8 opAct07 fn fn-male">
                <div class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/user.svg');"></div>
                <div class="formResult elz d-block"><?=htmlspecialchars($content['title'])?></div>
            </div>
        </div>
    </div>
</div>