<div class="counterAgentSuggestion elz d-block pVVar r3 cur-pointer bg bg-primary bgL5 bgHovL10 bgSel bgSel-secondary fnSel fnSel-secondary-t bsh-default1">
    <div class="elz d-flex dir-y gap8 pV8 pH16">
        <div class="elz d-block bold">ООО "Наука-Связь"</div>
        <div class="elz d-flex f-wrap gapH16 gapV8">
            <div class="elz d-flex gap8">
                <div class="elz d-block bold">ИНН:</div>
                <div class="elz d-block">7710189466</div>
            </div>
            <div class="elz d-flex gap8">
                <div class="elz d-block bold">КПП:</div>
                <div class="elz d-block">772401001</div>
            </div>
        </div>
    </div>
</div>