<div class="elz admIndexWrap">
    <div class="elz strCLSitem">
        <div class="elz elzIcon acpLogo">
            <i class="elz main elzIc ic-acp-logo"></i>
        </div>
        <div class="elz strCLSitem al-center marVLarge admIndexContent">
            <div class="elz strCLSitem fn-24">
                <p class="bb p">Root Control panel</p>
            </div>
            <div class="elz strCLSitem fn-12">
                <p class="bb p">Для начала работы выберите один из пунктов меню</p>
            </div>
        </div>
    </div>
</div>