
<?if(!isset($id)):?>
    <?$id = \Core\Builder\MustacheForms::getNextId()?>
<?endif;?>

<div<?if(isset($id)):?> id="<?=$id?>"<?endif;?> class="elizaRcpUploaderSystemContainer elz elzPicPrev fill borBelow elzPLT notInited" data-br="dark 100">
    <form style="display:none;" enctype="multipart/form-data" method="post" action="<?=$action?>" data-action="<?=$action?>"<?if(isset($imageSlave)):?> data-slave="<?=$imageSlave?>"<?endif;?>>
        <input class="elizaRcpUploaderSystemInput" type="file" name="image" id="<?=$id?>" accept="image/*" />
    </form>
    <input class="elizaRcpUploaderSystemHidden" type="hidden" name="<?=$name?>" />
    <div class="prevIn" data-title="<?=$title ?? ''?>" data-subtitle="<?=$subtitle ?? ''?>" data-default="<?=$imageDefault?>"><?if($imageSrc):?><img class="elz image" src="<?=$imageSrc?>" width="<?=$width?>" height="<?=$height?>" /><?endif;?></div>
    <ul class="elz elzCLSoverControls hidden horizontal top">
        <li class="elizaRcpUploaderSystemLabelDelete elz cntrlItem right link<?if($imageDefault == $imageSrc):?> hide<?endif;?>" title="Удалить">
            <div class="elz elzIcon small smallest">
                <i class="elz main smallest elzIc ic-cross"></i>
            </div>
        </li>
        <li class="elizaRcpUploaderSystemLabelUpload elz cntrlItem right link" title="Загрузить новое">
            <div class="elz elzIcon smallest">
                <i class="elz main smallest elzIc ic-upload"></i>
            </div>
        </li>
    </ul>
</div>