<?php $empty = $empty ?? ''?>
<div class="pmContentExpandContainer formWrap elz d-flex a-H f-wrap gapH16 gapV8 pV16 borT1 br br-primary brL-10 brLInvD showSelOut hideSelOut invSelOut showHovOut" data-name="<?=$name?>">
    <div class="elz d-block fb120 bold"><?=$title?>:</div>
    <div class="elz p-rel d-flex dir-y a-V fb320 grow hmn18">
        <div class="elz p-abs p-F d-flex dir-y a-V mV-10 showSelIn z1">
            <form method="post" action="<?=$action?>" class="elz d-grid grTV010 grPos fn fn-primary-t fnL20 s100p fnLInvD fnHovL10 fnFow-focus fnFowL0">
                <input type="text"
                       name="<?=$name?>"
                       value="<?=htmlspecialchars($content)?>"
                       class="elz elzInput d-block grPin grY2 s100p bor1 pL16 pR40 r3 fn12 ellipsis trns2 invPssSib
                              bg bg-primary bgL10 bgLInvD
                              br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                              fn fn-primary-t">
                <span class="elz d-flex grPin grY2 a-H bor1 pH7 z6 evNone">
                    <span class="elz p-rel growX d-flex a-PR">
                        <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                            <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                            </span>
                        </button>
                    </span>
                </span>
            </form>
        </div>
        <div class="formResult elz d-block invSelIn pR40<?if($empty && !$content):?> hide<?endif;?>"><?=htmlspecialchars($content)?></div>
        <div class="formEmpty elz p-rel d-block dir-y a-V hmn18<?if(!$empty || $content):?> hide<?endif;?>">
            <div class="elz d-flex a-H lh10 f-wrap gap8 fn11">
                <div class="elz d-flex a-X gap8 al-center pV6 pH8 r3 fn11 bg bg-error fn fn-error-t">
                    <div class="elz d-block"><?=$empty?></div>
                </div>
            </div>
        </div>
        <div title="Редактировать" class="formToggle elz p-abs p-R d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5 hideSelIn showHovIn">
            <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/pencil.svg');"></div>
        </div>
    </div>
</div>