<?return [
    'menu_auth_title' => 'Авторизация',
    'menu_auth_descr' => 'Войдите в систему',
    'menu_register_title' => 'Регистрация',
    'menu_register_descr' => 'Новый пользователь',
    'menu_remind_title' => 'Восстановление пароля',
    'menu_remind_descr' => 'Забыли пароль? Мы напомним',
    'menu_settings_title' => 'Настройки',
    'menu_settings_descr' => 'Управляйте настройками аккаунта',
    'menu_tpedit_title' => 'Редактор текста',
    'menu_tpedit_descr' => 'Редактирование текстовых шаблонов',
    'menu_rdedit_title' => 'Редактор дорог',
    'menu_rdedit_descr' => 'Редактирование дорог',
    'menu_isedit_title' => 'Редактор объектов',
    'menu_isedit_descr' => 'Редактирование объектов',
    'menu_txedit_title' => 'Редактор текстур',
    'menu_txedit_descr' => 'Редактирование текстур',
    'menu_bledit_title' => 'Редактор переходов',
    'menu_bledit_descr' => 'Редактирование переходов',
    'menu_icedit_title' => 'Редактор иконок',
    'menu_icedit_descr' => 'Редактирование иконок',
    'menu_logout_title' => 'Выход',
    'menu_logout_descr' => 'Выйти из системы'
];