<?return [
    'menu_auth_title' => 'Authorization',
    'menu_auth_descr' => 'Log in to rpginferno.com',
    'menu_register_title' => 'Registration',
    'menu_register_descr' => 'Create new account',
    'menu_remind_title' => 'Remind password',
    'menu_remind_descr' => 'Forgot password? We`ll remind you',
    'menu_settings_title' => 'Settings',
    'menu_settings_descr' => 'Manage your account settings',
    'menu_tpedit_title' => 'Text editor',
    'menu_tpedit_descr' => 'Edit text templates',
    'menu_isedit_title' => 'Object editor',
    'menu_isedit_descr' => 'Edit color schemes',
    'menu_rdedit_title' => 'Road editor',
    'menu_rdedit_descr' => 'Custom road styles for hex map',
    'menu_txedit_title' => 'Texture editor',
    'menu_txedit_descr' => 'Create custom textures',
    'menu_bledit_title' => 'Texture blender',
    'menu_bledit_descr' => 'Create texture blendings',
    'menu_icedit_title' => 'Icon editor',
    'menu_icedit_descr' => 'Any icon you need',
    'menu_logout_title' => 'Logout',
    'menu_logout_descr' => 'Log out from rpginferno.com'
];