<?php $placeHolder = $this->view->getVar('mainPlaceHolderRight')?>

<div class="elz d-flex grow">
    <div class="elz d-flex growX r3 bg bg-primary bgL5 bsh-default1">
        <div class="elz d-flex grow dir-y a-X p16 gap16">
            <div class="elz p-rel d-block mskBef mskBef-contain s120 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/<?=$placeHolder['icon']?>.svg');"></div>
            <div class="elz d-block al-center fn16"><?=$placeHolder['title']?></div>
        </div>
    </div>
</div>