<div class="elz elizeUI p-fixed p-T w100p hEP fn12 fn-roboto fn fn-primary-t">

    <div class="elz elizeEP p-rel d-flex hEP bg bg-EP fn fn-EP-t visHovOut5">
        <div class="elz d-grid dir-y gap8 pH8 or2 grow"></div>



        <div class="elz elizeTaskbar d-grid dir-y gap8 pH8 or1 noShrink">

            <div class="elz elizeAction p-rel d-flex a-X">
                <div class="elz elizeOverMenuToggler p-rel d-flex a-X s40 rCircle oH cur-pointer opAct07">
                    <img alt="" class="elz d-block s100p" src="https://cdn.discordapp.com/avatars/132364399091384321/37f7ec573cc999125e71661b0d5c1c7d.png" />
                    <div class="elz p-abs d-grid gap4 a-X p-F trns visHovIn5">
                        <div class="elz d-block bg bg-white w20 h2 r2 bshD bsh-itext1"></div>
                        <div class="elz d-block bg bg-white w20 h2 r2 bshD bsh-itext1"></div>
                        <div class="elz d-block bg bg-white w20 h2 r2 bshD bsh-itext1"></div>
                    </div>
                </div>
            </div>

            <div class="elz p-rel d-flex a-X borB3 pT3 br br-red">
                <div class="elz p-rel d-flex a-X s40 rCircle oH cur-pointer opAct07 bg bg-red fn fn-white">
                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" title="Активный" style="--elzMsk: url('https://lelouch.ru/uploads/icons/notification.svg');"></div>
                </div>
            </div>

        </div>



        <div class="elz d-grid dir-y gap8 pH8 or3 noShrink">

            <div class="elz hubMenuTrigger p-rel d-flex a-X hideSelOut showSelOut sel">
                <div class="elz d-flex a-X s40 rCircle oH cur-pointer opAct07 fnHov fnHovL15">
                    <div class="elz d-block hideSelIn p-abs mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/cross1.svg');"></div>
                    <div class="elz p-rel showSelIn d-grid gap6 a-X">
                        <div class="elz d-block bg bg-white w20 h2 r2"></div>
                        <div class="elz d-block bg bg-white w20 h2 r2"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <div id="elizaINTNotify" class="elz d-block p12 lh12 al-center trns2 trnsVis tsh-itext1 bg bg-success fn fn-success-t op0 invisible v2"></div>









    <div class="elz elizeOverMenu p-fixed">

        <div class="elz elizeOverMenuOverlay elizeOverMenuToggler p-fixed d-block p-F cur-alias bg bg-black bgA50 trns4"></div>

        <div class="elz elizeMenu uniScroll scrollSimple d-grid p-fixed h100p p-V pi-R bg bg-primary fn fn-primary-t">
            <div class="elz uniScrollIn oAuto p-rel d-flex dir-y h100p scrollHideFine"><!-- class .scrollHide чтобы скрыть скроллбар -->

                <div class="elz elizeProfileWrap p-sticky d-block p-T noShrink opHovOut bg bg-primary z2">
                    <div class="elz p-rel d-block uAspect x21y9">
                        <div class="elz p-abs d-flex p-F a-EB avHeadCutMask l120 bg bg-primary bgL-10 bgLInvD z1">

                            <div class="elz p-rel d-flex a-X smn56 op025 opHovIn10 trns">
                                <div class="elz elizeOverMenuToggler d-flex a-X s32 cur-pointer rCircle bg bg-black bgA50 bgHovA80 fn fn-white fnL-10 fnHovL0 opAct07 trns trnsStyle" title="Закрыть">
                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/cross1.svg');"></div>
                                </div>
                            </div>

                        </div>
                        <div class="p-abs d-flex a-ED p-F pH16">
                            <div class="p-rel d-flex a-H pH4">

                                <div class="elz uAvatar d-block p-abs s120">
                                    <div class="elz avCutMask p-abs p-F oH rCircle">
                                        <img class="elz d-block s100p rCircle" alt="" src="https://cdn.discordapp.com/avatars/132364399091384321/37f7ec573cc999125e71661b0d5c1c7d.png"/>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="elz elizeMenuWrap p-rel d-block grow">

                    <div class="elz elizeMenuList z1 p-abs p-AT d-block hmn100p bg bg-primary">

                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-blue fn fn-white fnL-10 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                    <div class="elz elzItemNext p-rel d-flex a-X s56 borL1 mL8 cur-pointer op025 opHov10 opAct07 trns">
                                        <div class="elz p-abs p-H d-flex h24 borL1 br br-CC trns op0 opHovIn10"></div>
                                        <div class="elz d-block p-rel mskBef s12 cFillBef bgBef-CC deg90" style="--elzMsk: url('https://lelouch.ru/uploads/icons/arrow2.svg');"></div>
                                    </div>
                                </div>

                            </div>



                            <div class="elz elizeMenuList z1 p-abs p-AT d-block hmn100p bg bg-primary">

                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz elzItemBack p-rel d-flex hmn56 bg bgL-8 bgHovL-12 bgLInvD cHovOut opHovOut showHovOut hideHovOut">
                                            <div class="elz p-rel d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-blue fn fn-white fnL-10 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC hideHovIn" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC deg270 showHovIn" style="--elzMsk: url('https://lelouch.ru/uploads/icons/arrow2.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11 hideHovIn">Редактирование шаблонов</div>
                                                    <div class="elz d-block pV2 fn11 bold showHovIn">Вернуться назад</div>
                                                </div>
                                            </div>
                                            <div class="elz p-rel d-flex a-X s56 borL1 mL8 cur-pointer op025 opHov10 opAct07 trns">
                                                <div class="elz p-abs p-H d-flex h24 borL1 br br-CC trns op0 opHovIn10"></div>
                                                <div class="elz d-block p-rel mskBef s12 cFillBef bgBef-CC deg90" style="--elzMsk: url('https://lelouch.ru/uploads/icons/cross1.svg');"></div>
                                            </div>
                                            <div class="elz p-abs p-F borV1 br br-primary brL-12 brLInvD evNone"></div>
                                        </div>

                                    </div>
                                </div>

                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-green fn fn-white fnL-10 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                            <div class="elz elzItemNext p-rel d-flex a-X s56 borL1 mL8 cur-pointer op025 opHov10 opAct07 trns">
                                                <div class="elz p-abs p-H d-flex h24 borL1 br br-CC trns op0 opHovIn10"></div>
                                                <div class="elz d-block p-rel mskBef s12 cFillBef bgBef-CC deg90" style="--elzMsk: url('https://lelouch.ru/uploads/icons/arrow2.svg');"></div>
                                            </div>
                                        </div>

                                    </div>



                                    <div class="elz elizeMenuList z1 p-abs p-AT d-block hmn100p bg bg-primary">

                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz elzItemBack p-rel d-flex hmn56 bg bgL-8 bgHovL-12 bgLInvD cHovOut opHovOut showHovOut hideHovOut">
                                                    <div class="elz p-rel d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-green fn fn-white fnL-10 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC hideHovIn" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC deg270 showHovIn" style="--elzMsk: url('https://lelouch.ru/uploads/icons/arrow2.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11 hideHovIn">Редактирование шаблонов</div>
                                                            <div class="elz d-block pV2 fn11 bold showHovIn">Вернуться назад</div>
                                                        </div>

                                                    </div>
                                                    <div class="elz p-rel d-flex a-X s56 borL1 mL8 cur-pointer op025 opHov10 opAct07 trns">
                                                        <div class="elz p-abs p-H d-flex h24 borL1 br br-CC trns op0 opHovIn10"></div>
                                                        <div class="elz d-block p-rel mskBef s12 cFillBef bgBef-CC deg90" style="--elzMsk: url('https://lelouch.ru/uploads/icons/cross1.svg');"></div>
                                                    </div>
                                                    <div class="elz p-abs p-F borV1 br br-primary brL-12 brLInvD evNone"></div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz d-block pH16 pV12 fn10 uppercase bold bg bg-primary bgL-10 bgLInvD">Редакторы</div>

                                            </div>
                                        </div>

                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <div class="elz d-block elizeMenuItem">
                                            <div class="elz p-rel d-block elizeItemInner">

                                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                        <div class="d-flex a-X s56 mH8">
                                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                                <div class="elz d-flex a-X dsh-text3">
                                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>





                                </div>

                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz d-block pH16 pV12 fn10 uppercase bold bg bg-primary bgL-10 bgLInvD">Редакторы</div>

                                    </div>
                                </div>

                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="elz d-block elizeMenuItem">
                                    <div class="elz p-rel d-block elizeItemInner">

                                        <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                            <div class="elz d-flex a-H growX cur-pointer opAct07">
                                                <div class="d-flex a-X s56 mH8">
                                                    <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                        <div class="elz d-flex a-X dsh-text3">
                                                            <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                                    <div class="elz d-block pV2 fn14">Редактор текста</div>
                                                    <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>





                        </div>

                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz d-block pH16 pV12 fn10 uppercase bold bg bg-primary bgL-10 bgLInvD">Редакторы</div>

                            </div>
                        </div>

                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="elz d-block elizeMenuItem">
                            <div class="elz p-rel d-block elizeItemInner">

                                <div class="elz p-rel d-flex hmn56 bgHov bgHov-primary bgHovL-5 bgHovLInvD cHovOut opHovOut">
                                    <div class="elz d-flex a-H growX cur-pointer opAct07">
                                        <div class="d-flex a-X s56 mH8">
                                            <div class="d-flex a-X s40 rCircle bg bg-primary bgL-10 bgLInvD fn fn-white fnL-5 fnHovInL0" title="Галочка на иконке типа">
                                                <div class="elz d-flex a-X dsh-text3">
                                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('https://lelouch.ru/uploads/icons/checkmark.svg');"></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="elz d-block growX lh12 fnHovIn fnHovIn-primary-t fnHovInL-10 fnHovInLInvD">
                                            <div class="elz d-block pV2 fn14">Редактор текста</div>
                                            <div class="elz d-block pV2 fn11">Редактирование шаблонов</div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>

                </div>

            </div>
        </div>



    </div>
</div>