<?$enableClass = ""?>
<?$enableColor = "grey 600"?>

<?if($route_disabled == 0):?>
    <?$enableClass = " routeEnabled"?>
    <?$enableColor = "green"?>
<?endif;?>

<tr class="rcpRouteItem" data-id="<?=$route_id?>">
    <td class="compressed">
        <div class="elz strCLSitem mar-RMedium">
            <i class="elz elzIcon medium cur-move">
                <i class="elz elzIc main smallest ic-move-v"></i>
            </i>
        </div>
    </td>
    <td>
        <?=\Core\Builder\MustacheForms::input('text', 'Шаблон маршрута', '', '', '', 'pattern', $route_pattern, 'small')?>
    </td>
    <td>
        <?=\Core\Builder\MustacheForms::textArea('JSON объект', '', '', '', 'json', $route_json, 'row1', 'small')?>
    </td>
    <td class="compressed">
        <div class="elz strCLSitem flexible mar-LLarge">
            <div class="elz strCLSitem marLSmall">
                <i class="rcpRouteSaver elz elzIcon medium rad elzPLT icLink link hovLight" data-bg="blue">
                    <i class="elz elzIc main smallest ic-save shD elzPLT" data-fn="white"></i>
                </i>
            </div>
            <div class="elz strCLSitem marLSmall">
                <i class="rcpRouteEnabler elz elzIcon medium rad elzPLT icLink link hovLight<?=$enableClass?>" data-bg="<?=$enableColor?>">
                    <i class="elz elzIc main smallest ic-powercord shD elzPLT" data-fn="white"></i>
                </i>
            </div>
            <div class="elz strCLSitem marLSmall">
                <i class="rcpRouteDelete elz elzIcon medium rad elzPLT icLink link hovLight" data-bg="red">
                    <i class="elz elzIc main smallest ic-cross shD elzPLT" data-fn="white"></i>
                </i>
            </div>
        </div>
    </td>
</tr>