<?php $itemsList = $items ?? []?>
<?php $hasItems = sizeof($itemsList)?>
<li class="dictItem elz uExpItem" data-id="<?=$service_dict_id?>">
    <div class="dictWrap elz uExpWrap d-block r3 bg bg-primary bgL5 bgHovL7 bsh-default1 showSelOut5 hideSelOut5<?/* sel*/?>">
        <div class="elz d-flex f-wrap a-H gap8 p8">
            <div class="elz p-rel d-flex growMax s-S fb200">
                <div class="dictExpand elz d-flex grow a-H mAL-8 pAL8 cur-pointer opAct07">
                    <div class="elz d-flex a-X s32">
                        <div class="mskIcon elz d-block p-rel noShrink mskBef s12 cFillBef bgBef-CC deg180 hideSelIn5" style="--elzMsk: url('/design/icons/arrow2.svg');"></div>
                        <div class="mskIcon elz d-block p-rel noShrink mskBef s12 cFillBef bgBef-CC showSelIn5" style="--elzMsk: url('/design/icons/arrow2.svg');"></div>
                    </div>
                    <div class="dictTitle elz d-block fn16 grow"><?=$dict_title?></div>
                </div>
                <form action="?act=dict_update&id=<?=$service_dict_id?>"
                      method="post"
                      class="dictUpdateForm elz p-abs p-H d-grid grPos grTV010 fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0 hide">
                    <input type="text"
                           name="title"
                           value="<?=$dict_title?>"
                           placeholder="Введине название категории"
                           class="elz elzInput d-block grPin grY2 w100p bor1 r3 h40 pL40 pR16 fn12 ellipsis trns2 invPssSib
                                  bg bg-primary bgL10 bgLInvD
                                  br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                  fn fn-primary-t">
                    <span class="elz d-flex a-H grPin grY2 bor1 pH7 z6 evNone">
                        <span class="elz p-rel d-flex a-X s24 trns2">
                            <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/font.svg');"></span>
                        </span>
                        <span class="elz p-rel growX d-flex a-PR">
                            <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                                <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                    <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                                </span>
                            </button>
                        </span>
                    </span>
                </form>
            </div>

            <?php $this->view->partial('services/partials/status_select', ['select_class' => 'dictStatusChange', 'service_status_id' => $service_status_id, 'linked_count' => (int)($active_count ?? 0)])?>
            <div class="elz d-flex f-wrap gap8">
                <div title="Редактировать" class="dictEdit elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5 fnSel fnSel-ok-t bgSel bgSel-ok">
                    <div class="mskIcon evNone elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/pencil.svg');"></div>
                </div>
                <div title="Удалить" class="dictDelete elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                    <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/cross1.svg');"></div>
                </div>
            </div>
        </div>


        <div class="dictItemsWrap elz d-block borT1 br br-primary brL-10 brLInvD brLF5 brFD showSelIn5<?if($service_status_id == 3):?> uDisabled evNone<?endif;?>">
            <div class="dictItemsList elz d-flex dir-y pV4 borB1 br br-primary brL-10 brLInvD brLF10 brFD cEmpty"><?foreach($itemsList as $item):?><?$this->view->partial('services/partials/dict_item', $item)?><?endforeach;?></div>
            <div class="dictItemsAdd elz d-flex dir-y pV4 bg bg-primary bgL-3 bgLInvD ">
                <?$this->view->partial('services/partials/dict_item', ['service_dict_id' => $service_dict_id, 'service_status_id' => 1])?>
            </div>
        </div>
    </div>
</li>