<?php $servicesList = $services ?? []?>
<?php $hasServices = sizeof($servicesList)?>
<li class="serviceCategory elz uExpItem" data-id="<?=$service_category_id?>">
    <div class="categoryWrap elz uExpWrap d-block pVar r3 bg bg-primary bgL5 bsh-default1 showSelOut">
        <div class="elz d-flex f-wrap a-H gap8">
            <div class="elz p-rel d-flex a-H grow fb200">
                <div class="elz d-flex a-X s32">
                    <div class="mskIcon elz d-block p-rel noShrink mskBef s14 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/list.svg');"></div>
                </div>
                <div class="categoryTitle elz d-block fn16 grow"><?=$category_title?></div>
                <form action="?act=category_update&id=<?=$service_category_id?>"
                      method="post"
                      class="categoryUpdateForm elz p-abs p-H d-grid grPos grTV010 fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0 showSelIn">
                    <input type="text"
                           name="title"
                           value="<?=$category_title?>"
                           placeholder="Введине название категории"
                           class="elz elzInput d-block grPin grY2 w100p bor1 r3 h40 pL40 pR16 fn12 ellipsis trns2 invPssSib
                                  bg bg-primary bgL10 bgLInvD
                                  br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                  fn fn-primary-t">
                    <span class="elz d-flex a-H grPin grY2 bor1 pH7 z6 evNone">
                        <span class="elz p-rel d-flex a-X s24 trns2">
                            <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/font.svg');"></span>
                        </span>
                        <span class="elz p-rel growX d-flex a-PR">
                            <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                                <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                    <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                                </span>
                            </button>
                        </span>
                    </span>
                </form>
            </div>
            <div class="elz d-flex f-wrap gap8">
                <div title="Редактировать" class="categoryEdit elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5 bgSel bgSel-ok fnSel fnSel-t-ok">
                    <div class="mskIcon evNone elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/pencil.svg');"></div>
                </div>
                <div class="elz p-rel d-flex a-X showSelOut1">
                    <div title="Добавить" class="categoryServiceAdd elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                        <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/plus2.svg');"></div>
                    </div>
                    <form action="?act=service_create&category_id=<?=$service_category_id?>"
                          data-cid="<?=$service_category_id?>"
                          method="post"
                          class="categoryServiceAddForm elz p-abs p-R d-grid w360 grPos grTV010 fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0 showSelIn1">
                        <input type="text"
                               name="title"
                               value=""
                               placeholder="Введите название услуги"
                               class="elz elzInput d-block grPin grY2 w100p bor1 r3 h40 pL40 pR16 fn12 ellipsis trns2 invPssSib
                                      bg bg-primary bgL10 bgLInvD
                                      br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                      fn fn-primary-t">
                        <span class="elz d-flex a-H grPin grY2 bor1 pH7 z6 evNone">
                            <span class="elz p-rel d-flex a-X s24 trns2">
                                <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/plus2.svg');"></span>
                            </span>
                            <span class="elz p-rel growX d-flex a-PR">
                                <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                                    <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                        <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                                    </span>
                                </button>
                            </span>
                        </span>
                    </form>
                </div>
                <div title="Удалить" class="categoryDelete elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                    <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/cross1.svg');"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="services elz uExpNode  bg bg-primary bgL10 bgLInvD br br-primary brL-10 brLInvD<?if(!$hasServices):?> hide<?endif;?>"></div>
    <ul class="services elz uExpList<?if(!$hasServices):?> hide<?endif;?>">
<?if($hasServices):?>
    <?foreach($servicesList as $service):?>
        <?$this->view->partial('services/partials/service_item', $service)?>
    <?endforeach;?>
<?endif;?>
    </ul>
</li>