<?php $service_status_id = $service_status_id ?? 1?>
<?php list($statusColor, $statusLockMap) = [
    1 => ['danger', []],
    2 => ['success', [1 => 1]],
    3 => ['error',   [1 => 1, 2 => 1]]
][$service_status_id]?>

<?php $linkedItems = $linked_count ?? 0?>
<select<?if(isset($status_name)):?> name="<?=$status_name?>"<?endif;?> class="<?=($select_class ?? '')?> elz d-block pV5 pH8 grow fb120 r3 cur-pointer opAct07 al-center fn11 bg bg-<?=$statusColor?> bgHovL5 fn fn-<?=$statusColor?>-t">
    <option value="1"<?if($service_status_id == 1):?> selected="selected"<?endif;?><?if($service_status_id == 3 || ($statusLockMap[1] ?? 0)):?> disabled="disabled"<?endif;?>>Черовновик</option>
    <option value="2"<?if($service_status_id == 2):?> selected="selected"<?endif;?><?if($service_status_id == 3 || !$linkedItems):?> disabled="disabled"<?endif;?>>Активна</option>
    <option value="3"<?if($service_status_id == 3):?> selected="selected"<?endif;?><?if(0 < $linkedItems):?> disabled="disabled"<?endif;?>>Архив</option>
</select>