<?php $clsId = 'seg'.$international_segment_id?>
<li class="segmentItem elz uExpItem" data-id="<?=$international_segment_id?>" data-parent="<?=$parent_international_segment_id?>">
    <div class="elz uExpWrap p-rel d-flex f-wrap gap8 a-H hmn48 pAR8 pL16 r3 bgHov bgHov-primary">
        <div class="<?=$clsId?> segmentTitle elz d-block grow"><?=$segment_title?></div>
<?if(isset($counteragent_count)):?>
        <div class="elz d-flex f-wrap a-H">
            <div class="elz d-flex a-H gap4 p4 r3 fn11 bold bg bg-primary bgL-5">
                <div class="mskIcon elz d-block p-rel noShrink mskBef s12 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/user.svg');"></div>
                <div class="elz d-block"><?=$counteragent_count?></div>
            </div>
        </div>
<?endif;?>
        <div class="elz d-flex a-X gap8">
<?if(isset($can_edit)):?>
            <div class="segmentAddWrap elz p-rel d-flex a-X">
                <div title="Добавить сегмент" class="segmentAddToggle elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                    <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/plus2.svg');"></div>
                </div>
                <form method="post" action="?act=segment_create" class="segmentAddForm elz p-abs pi-R d-block r3 w240 p8 bsh-default3 bgp bg bg-primary bgL10 bor1 br br-black brA10 hide">
                    <div class="elz d-grid grPos fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0">
                        <input type="hidden" name="parent_id" value="<?=$international_segment_id?>" />
                        <input type="text"
                               name="title"
                               value=""
                               placeholder="Название сегмента"
                               class="elz elzInput d-block grPin grY2 w100p bor1 h32 pH8 r3 fn12 ellipsis trns2 invPssSib
                                      bg bg-primary bgL10 bgLInvD
                                      br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                      fn fn-primary-t">
                        <span class="elz d-flex grPin grY2 a-H bor1 pH7 z6 evNone">
                            <span class="elz p-rel growX d-flex a-PR">
                                <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                                    <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                        <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/plus2.svg');"></span>
                                    </span>
                                </button>
                            </span>
                        </span>

                    </div>
                </form>
            </div>
            <div class="segmentEditWrap elz p-rel d-flex a-X">
                <div title="Добавить сегмент" class="segmentEditToggle elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                    <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/pencil.svg');"></div>
                </div>
                <form method="post" action="?act=segment_update&id=<?=$international_segment_id?>" class="segmentEditForm elz p-abs pi-R d-block r3 w240 p8 bsh-default3 bgp bg bg-primary bgL10 bor1 br br-black brA10 hide">
                    <div class="elz d-grid grPos fn fn-primary-t fnL20 fnLInvD fnHovL10 fnFow-focus fnFowL0">
                        <input type="hidden" name="parent_id" value="<?=$parent_international_segment_id?>" />
                        <input type="text"
                               name="title"
                               value="<?=$segment_title?>"
                               placeholder="Название сегмента"
                               class="elz elzInput d-block grPin grY2 w100p bor1 h32 pH8 r3 fn12 ellipsis trns2 invPssSib
                                      bg bg-primary bgL10 bgLInvD
                                      br brLInvD br-primary brL-10 brHovL-20 brFoc-focus brFocL0
                                      fn fn-primary-t">
                        <span class="elz d-flex grPin grY2 a-H bor1 pH7 z6 evNone">
                            <span class="elz p-rel growX d-flex a-PR">
                                <button type="submit" class="elz p-rel d-flex a-H cur-pointer opAct07">
                                    <span class="elz p-rel d-flex a-X s24 r2 evAuto">
                                        <span class="elz p-rel d-block mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/save.svg');"></span>
                                    </span>
                                </button>
                            </span>
                        </span>

                    </div>
                </form>
            </div>
            <div title="Удалить сегмент" class="segmentDelete elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5">
                <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/cross1.svg');"></div>
            </div>
<?elseif(isset($can_select)):?>
            <div title="Выбрать сегмент" class="segmentSelect elz d-flex a-X cur-pointer opAct07 s36 rRound bgHov bgHov-primary bgHovL-5 bgSel bgSel-success fnSel fnSel-success-t<?if($segment_selected):?> sel<?endif;?>" data-id="<?=$international_segment_id?>">
                <div class="mskIcon elz d-block p-rel noShrink mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/checkmark3.svg');"></div>
            </div>
<?endif;?>
        </div>

    </div>
<?$list = $list ?? []?>
<?$map = $map ?? []?>
<?$listLen = sizeof($list)?>
<?$hideClass = $listLen ? '' : ' hide'?>
    <input type="checkbox" class="<?=$clsId.$hideClass?> listLenToggle elz uExpCheck" <?=(!((int)$parent_international_segment_id) ? ' checked="checked"' : '')?>>
    <div class="<?=$clsId.$hideClass?> listLenToggle elz uExpNode medium bg bg-primary bgL10 bgLInvD br br-primary brL-10 brLInvD"></div>

    <ul class="<?=$clsId.$hideClass?> listLenToggle elz uExpList">
<?for($a = 0; $a < $listLen; $a++):?>
    <?$segment = $list[$a]?>
    <?$segment['list'] = $map[$segment['international_segment_id']] ?? []?>
    <?$segment['map'] = $map?>
    <?$this->view->partial('international_segments/partials/segment_item', $segment)?>
<?endfor;?>
    </ul>
</li>