<div class="elz pmTpl d-grid hmn100p overMenuHidden">
    <!--МЕНЮ-->
    <!--КОНТЕНТ-->
    <div id="TEST_overMenu1" class="elz pmTplSide menuStatic uniScroll scrollSimple p-sticky p-TEP d-grid hmx100hEP lh12 bg bg-primary">
        <div class="elz uniScrollIn oAuto scrollHideFine">

            <div class="elz d-flex f-wrap a-T gapVar pVar">

                <div class="elz d-block grow fb320 pVVar r3 bg bg-primary bgL5 bsh-default1">
                    <h2 class="elz d-flex a-X gap8 fn16 pV8 pH16 hmn36">
                        <span class="elz d-block growX">Сервисы</span>
                    </h2>
                    <ul class="elz d-block">

                        <li class="elz d-block">
                            <a href="/partners" title="" class="elz d-flex a-H cur-pointer pV8 hmn36 bgHov bgSel bgHov-primary bgHovL-10 bgLInvD opAct07 bgSel-secondary fnSel fnSel-secondary-t">
                                <div class="elz d-flex a-X w40">
                                    <div class="elz d-block p-rel mskBef s16 cFillBef bgBef-CC" style="--elzMsk: url('/design/icons/users1.svg');"></div>
                                </div>
                                <div class="elz d-block growX">Партнеры</div>
                            </a>
                        </li>


                    </ul>
                </div>

            </div>

        </div>
    </div>



    <div class="elz pmTplContent mL-Var">

        <div class="elz d-flex dir-y gapVar pVar">


            <div class="elz d-block m-Var">
                <img class="elz d-block wAuto wmx100p r3" alt="" src="images/crm_dashboard.png" />
            </div>



        </div>

    </div>







</div>